### ISSUE TITLE
Memory allocate problem.

### ISSUE THREAD

**Issue by xAyman** [btbd/smap#13]
I tested smap in FortniteClient-Win64-Shipping,
It says : failed to allocate virtual memory for headers (or something like that, can't remember)
Any fixes please ?
Thanks.

**Comment by btbd** [comment]
@xAyman Implement a proper EAC/BE bypass.

**Comment by xAyman** [comment]
How, can you give me one please ?

**Comment by statichaha** [comment]
oof

**Comment by SleekZ** [comment]
lol
