### ISSUE TITLE
Unexpected instruction with jump/offset register

### ISSUE THREAD

**Issue by johnmc-ui** [btbd/smap#5]
[error at D:\smap-master\smap\translator.cpp:593] unexpected instruction with jump/offset register at 00000000000659EF (00000000000659F9)

My test dll is compiled msvc (2019)

> .text:00000001800659C7                 mov     [rbp+var_28], r11d
.text:00000001800659CB                 mov     [rbp+arg_8], r13d
.text:00000001800659CF                 cmp     eax, 1Eh        ; switch 31 cases
.text:00000001800659D2                 ja      loc_180066FD9   ; jumptable 00000001800659F9 default case
.text:00000001800659D8                 mov     edx, eax
.text:00000001800659DA
.text:00000001800659DA loc_1800659DA:                          ; CODE XREF: sub_180065930+763↓j
.text:00000001800659DA                 cdqe
.text:00000001800659DC                 lea     rcx, cs:180000000h
.text:00000001800659E3                 lea     r8, [r12+68h]
.text:00000001800659E8                 mov     ecx, ds:(off_180066FF0 - 180000000h)[rcx+rax*4]
.text:00000001800659EF                 lea     rax, cs:180000000h
.text:00000001800659F6                 add     rcx, rax
.text:00000001800659F9                 jmp     rcx             ; switch jump
.text:00000001800659FB ; ---------------------------------------------------------------------------
.text:00000001800659FB
.text:00000001800659FB loc_1800659FB:                          ; CODE XREF: sub_180065930+C9↑j
.text:00000001800659FB                                         ; DATA XREF: sub_180065930:off_180066FF0↓o
.text:00000001800659FB                 mov     edx, [r12+8]    ; jumptable 00000001800659F9 case 0
.text:0000000180065A00                 test    edx, edx
.text:0000000180065A02                 jnz     short loc_180065A11
.text:0000000180065A04                 mov     dword ptr [r12], 0Ch

**Comment by btbd** [comment]
I’m surprised MSVC would load cs:0 twice for the same jump table — even if the table entries needed cs:0, it seems easier to just preserve a register initially unless probably run out of volatile registers down the line. Anyways, good find. Will fix.

**Comment by btbd** [comment]
@johnmc-ui I wasn't able to reproduce a case like this, so could you test the possible fix in the [dev branch](https://github.com/btbd/smap/tree/dev)?

**Comment by johnmc-ui** [comment]
Hello, thanks for your time.
I'm getting this now

[-] analyzing sections...
[+] .text    > (0x1000, 0x11A200)
[error at D:\smap-master\smap\translation.h:101] failed to generate valid assembly for modified translation
        nop dword ptr [rcx+rax*1], eax
        at 00000000000665DB`

> .text:00000001800665B9                 mov     dword ptr [r12], 7
.text:00000001800665C1
.text:00000001800665C1 loc_1800665C1:                          ; CODE XREF: inflate+C9↑j
.text:00000001800665C1                                         ; DATA XREF: inflate:off_180067680↓o
.text:00000001800665C1                 test    dword ptr [r12+10h], 1000h ; jumptable 0000000180066089 case 7
.text:00000001800665CA                 jz      loc_180066656
.text:00000001800665D0                 test    esi, esi
.text:00000001800665D2                 jz      loc_18006754B
.text:00000001800665D8                 mov     edi, r13d
.text:00000001800665DB                 nop     dword ptr [rax+rax+00h]
.text:00000001800665E0
.text:00000001800665E0 loc_1800665E0:                          ; CODE XREF: inflate+656↓j
.text:00000001800665E0                 mov     eax, edi
.text:00000001800665E2                 inc     edi
.text:00000001800665E4                 movzx   r13d, byte ptr [rax+r14]
.text:00000001800665E9                 mov     rax, [r12+20h]
.text:00000001800665EE                 test    rax, rax
.text:00000001800665F1                 jz      short loc_18006660F
.text:00000001800665F3                 mov     rdx, [rax+30h]

**Comment by btbd** [comment]
Could you send the raw bytes for the `nop dword ptr [rax+rax+00h]` instruction? I'm not sure why the analyzer is trying to modify that instruction because it has no relative attributes.

**Comment by johnmc-ui** [comment]
.text:00000001800665DB 098 0F 1F 44 00 00  nop     dword ptr [rax+rax+00h]

**Comment by btbd** [comment]
Ah, the compiler wasted an extra byte for the `00` displacement when it could've just ignored displacement altogether. Fixed at f99ca660ecec2ee8b7e73344761996008205949a. Let me know if there are any other issues.

**Comment by johnmc-ui** [comment]
Hello, that seems to have fixed it! Thanks a lot.

**Comment by johnmc-ui** [comment]
Hello, sorry for pestering you again :/

I ran into this, this morning while implementing more stuff from my fw to test on some games

[error at D:\smap-master\smap\translation.h:101] failed to generate valid assembly for modified translation
        lea eax, [rcx
        at 000000000011A3BA

> .text:000000018011A3B2 41 8A C8                                mov     cl, r8b
.text:000000018011A3B5 45 84 C0                                test    r8b, r8b
.text:000000018011A3B8 74 37                                   jz      short loc_18011A3F1
.text:000000018011A3BA 41 8D 40 D0                             lea     eax, [r8-30h]
.text:000000018011A3BE 3C 09                                   cmp     al, 9
.text:000000018011A3C0 76 16                                   jbe     short loc_18011A3D8
.text:000000018011A3C2 41 8D 40 9F                             lea     eax, [r8-61h]
.text:000000018011A3C6 3C 19                                   cmp     al, 19h
.text:000000018011A3C8 76 0E                                   jbe     short loc_18011A3D8

**Comment by btbd** [comment]
Well, it's a bit concerning that the branch tracing found `r8` to be set as a base register when that makes no sense with a negative displacement (is the only way for 11A3BA to execute via a jump from below?) Anyways, we should only accept possible relative SIB instructions with a positive displacement. Try the fix in the dev branch (a1aeb619866075de7956d782dc247ed184fc4646).

**Comment by johnmc-ui** [comment]
Hello, sorry for the late reply, i just tested the fix and it seems to work now. Thank you!
