### ISSUE TITLE
Failed to generate valid assembly for modified translation

### ISSUE THREAD

**Issue by rohybrnta** [btbd/smap#8]
Compiler: Clang
Issue: [error at C:\smap\translation.h:101] failed to generate valid assembly for modified translation
        lea eax, [rcx
        at 00000000001720AA

Assembly:
```
.text:00000000001720A2                 mov     cl, r8b
.text:00000000001720A5                 test    r8b, r8b
.text:00000000001720A8                 jz      short loc_1720E1
**.text:00000000001720AA                 lea     eax, [r8-30h]**
.text:00000000001720AE                 cmp     al, 9
.text:00000000001720B0                 jbe     short loc_1720C8
.text:00000000001720B2                 lea     eax, [r8-61h]
```

**Comment by rohybrnta** [comment]
Same issue when using MSVC as compiler:

[error at C:\smap\translation.h:101] failed to generate valid assembly for modified translation
        lea eax, [rcx
        at 0000000000104EB2

```
.text:0000000000104EB0                 jz      short loc_104EE9
.text:0000000000104EB2                 lea     eax, [r8-30h]
.text:0000000000104EB6                 cmp     al, 9
.text:0000000000104EB8                 jbe     short loc_104ED0
.text:0000000000104EBA                 lea     eax, [r8-61h]
.text:0000000000104EBE                 cmp     al, 19h
.text:0000000000104EC0                 jbe     short loc_104ED0
.text:0000000000104EC2                 lea     eax, [r8-41h]
.text:0000000000104EC6                 cmp     al, 19h
.text:0000000000104EC8                 jbe     short loc_104ED0
```

**Comment by uItra** [comment]
Try the fix in the dev branch (a1aeb61).

**Comment by rohybrnta** [comment]
@ultra this works, thanks!

Sadly another issue remains: 
[error at C:\smap\translator.cpp:109] target process does not have dependency.dll loaded
- even though I have compiled using "Multithreaded (/MT)"
Any Idea on that?

**Comment by btbd** [comment]
@rohybrnta Is the dependency d3dcompiler_47?

**Comment by rohybrnta** [comment]
@btbd no its XINPUT9 from imgui

**Comment by rohybrnta** [comment]
If compiling with /MT does not work what else I could do? Loading these dll's manually using loadlib?

**Comment by btbd** [comment]
@rohybrnta XINPUT isn't available as a static library AFAIK so you can either casually inject the dependency into the target process since it is signed or just remove the XINPUT code from ImGui if you don't actually need it.

**Comment by rohybrnta** [comment]
@btbd Ty, how can I check which librarys are available as static librarys?

**Comment by btbd** [comment]
Use the `lib` command that comes with VS. If it lists DLLs then its requires those imports if its only objs then you can statically link the code.

![image](https://user-images.githubusercontent.com/22239674/71606223-0bd92100-2b3d-11ea-9394-f415a7e573c3.png)
